package ca.mcgill.ecse.biketourplus.javafx.fxml.controllers;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

public class FeatureSet8PageController {
	@FXML
	private TextField emailTextField;
	@FXML
	private TextField authCodeTextField;
	@FXML
	private TextField totalPriceTextField;
	@FXML
	private Button payButton;
	@FXML
	private Button calculateButton;

	// Event Listener on Button[#payButton].onAction
	@FXML
	public void payClicked(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#calculateButton].onAction
	@FXML
	public void calculateClicked(ActionEvent event) {
		// TODO Autogenerated
	}
}
